name: Deploy static site to GitHub Pages

on:
  push:
    branches: [ Deploy ]
  workflow_dispatch:

# Required permissions for GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload site artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Root contains only static assets (no build step required)
          path: '.'

      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4

    # Notes:
    # - This workflow assumes your static site lives at the repo root.
    # - Push to the Deploy branch (or use the Run Workflow button) to publish.
    # - After first successful run, ensure Pages is enabled under Settings > Pages with Source: GitHub Actions.
